name: Check
on:
  push:
    branches:
    - main
    - workflow_check
  pull_request:
    branches:
    - main
jobs:
  check:
    name: Check
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run dotnet restore
      run: dotnet restore

    - name: Run dotnet build
      run: >
        dotnet build
        --no-incremental
        --no-restore

    # -- this would need mech3ax present
    # - name: Run dotnet test
    #   run: dotnet test --no-restore --logger "console;verbosity=detailed"
